# This is a basic workflow to help you get started with Actions

name: dailyUpdate

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 0,6,12,18 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SetUp Python
        uses: actions/setup-python@v3.10
        
      - name: Install
        run: |
          pip3 install requests
          pip3 install datetime
          pip3 install pandas

      - name: Update
        run: |
          python3 dailyUpdate.py
          
      - name: pull And Push
        run: |-
          git diff
          git config --global user.email "2229840919@qq.com"
          git config --global user.name "0Xffff"
          git pull
          git add .
          git commit -m "hotpoint $(date +'%Y-%m-%d %H:%M')"
          git push
